import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>natta</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="max-w-7xl mx-auto lg:px-28 px-7 flex justify-center lg:justify-start items-center h-screen">
        <div className="relative md:pl-20 ">
          {/* title */}
          <div className="text-center md:text-left mb-24 md:mb-0">
            <div className="absolute hidden md:block md:w-[90px] lg:w-[117px] left-0 -top-16 lg:-left-2 lg:-top-24">
              <Circlesvg />
            </div>
            <h1 className="font-bold text-7.5xl md:text-8xl lg:text-10xl pb-3 lg:pb-4 tracking-wide md:tracking-normal">natta</h1>
            <p className="text-xl md:text-2xl lg:text-3xl font-bold tracking-wider lg:tracking-normal md:pl-2">
              the <span className="text-brand-primary underline">first</span> dating app
            </p>
          </div>
          {/* text */}
          <div className="w-[310px] md:w-[220px] lg:w-[310px] md:ml-[270px] lg:ml-[315px] md:-mt-7 pl-16 md:pl-0 relative mb-12 lg:mb-0">
            <div className="absolute left-2 -top-12 md:hidden w-16">
              <Circlesvg />
            </div>
            <p className="text-4xl lg:text-5.5xl font-semibold tracking-widest md:tracking-wide ">
              We’re still getting dressed, but{" "}
              <span className="text-brand-primary"> we’ll text you</span> when
              we’re ready...
            </p>
          </div>
          {/* buttons */}
          <div className="md:ml-[420px] lg:ml-[510px] md:-mt-20 lg:-mt-8 w-[225px] mx-auto md:w-[225px] lg:w-[290px] flex flex-col gap-y-2.5 items-center">
            <div className="bg-white/20 hover:bg-white/30 w-full p-2 lg:p-2.5 flex items-center gap-x-2.5 rounded-lg mb-2 lg:mb-[18px] ">
              <div className="w-6 md:w-8">
                <Call />
              </div>
              <input
                className="w-full h-full bg-transparent outline-none font-medium text-lg lg:text-2xl tracking-widest"
                placeholder="Drop Your Digits"
                type="text"
              />
            </div>
            <button className="bg-white/20 hover:bg-white/30 w-full p-1.5 lg:p-2.5 rounded-lg mb-2 font-medium text-lg leading-6 lg:text-2xl tracking-widest">
              Join the <span className="text-brand-primary">DateList</span>
            </button>
            <Link 
              href={"#"} 
              className="md:text-lg lg:text-xl font-medium text-center hover:text-brand-primary hover:underline transition-all duration-300 tracking-wide"
            >
              Got an invite code?
            </Link>
          </div>
        </div>
      </main>
    </>
  );
}

const Circlesvg = () => {
  return (
    <svg
      className="w-full h-full"
      width={116}
      height={116}
      viewBox="0 0 122 122"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <circle
        cx="61.1453"
        cy="61.145"
        r="32.08"
        stroke="white"
        strokeWidth="4.01"
      />
      <path
        d="M119.29 61.145C119.29 49.645 115.88 38.4033 109.491 28.8414C103.102 19.2795 94.0207 11.8269 83.3961 7.42602C72.7715 3.02517 61.0805 1.8737 49.8015 4.11724C38.5224 6.36078 28.162 11.8986 20.0303 20.0303C11.8986 28.162 6.36078 38.5224 4.11724 49.8015C1.8737 61.0805 3.02517 72.7715 7.42602 83.3961C11.8269 94.0207 19.2795 103.102 28.8414 109.491C38.4033 115.88 49.645 119.29 61.145 119.29"
        stroke="white"
        strokeWidth="4.01"
        strokeLinecap="round"
      />
    </svg>
  );
};

const Call = () => {
  return (
    <svg
    className="w-full h-full"
      width={33}
      height={33}
      viewBox="0 0 33 33"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path
        d="M30.209 25.2037C30.209 25.6987 30.099 26.2075 29.8652 26.7025C29.6315 27.1975 29.329 27.665 28.9302 28.105C28.2565 28.8475 27.514 29.3837 26.6752 29.7275C25.8502 30.0712 24.9565 30.25 23.994 30.25C22.5915 30.25 21.0927 29.92 19.5115 29.2462C17.9302 28.5725 16.349 27.665 14.7815 26.5237C13.1839 25.3551 11.6763 24.0682 10.2715 22.6737C8.88105 21.274 7.59863 19.771 6.43524 18.1775C5.30774 16.61 4.40024 15.0425 3.74024 13.4887C3.08024 11.9212 2.75024 10.4225 2.75024 8.9925C2.75024 8.0575 2.91524 7.16375 3.24524 6.33875C3.57524 5.5 4.09774 4.73 4.82649 4.0425C5.70649 3.17625 6.66899 2.75 7.68649 2.75C8.07149 2.75 8.45649 2.8325 8.80024 2.9975C9.15774 3.1625 9.47399 3.41 9.72149 3.7675L12.9115 8.26375C13.159 8.6075 13.3377 8.92375 13.4615 9.22625C13.5852 9.515 13.654 9.80375 13.654 10.065C13.654 10.395 13.5577 10.725 13.3652 11.0412C13.1865 11.3575 12.9252 11.6875 12.5952 12.0175L11.5502 13.1037C11.399 13.255 11.3302 13.4337 11.3302 13.6537C11.3302 13.7637 11.344 13.86 11.3715 13.97C11.4127 14.08 11.454 14.1625 11.4815 14.245C11.729 14.6987 12.1552 15.29 12.7602 16.005C13.379 16.72 14.039 17.4487 14.754 18.1775C15.4965 18.9062 16.2115 19.58 16.9402 20.1987C17.6552 20.8037 18.2465 21.2162 18.714 21.4637C18.7827 21.4912 18.8652 21.5325 18.9615 21.5737C19.0715 21.615 19.1815 21.6287 19.3052 21.6287C19.539 21.6287 19.7177 21.5462 19.869 21.395L20.914 20.3637C21.2577 20.02 21.5877 19.7587 21.904 19.5937C22.2202 19.4012 22.5365 19.305 22.8802 19.305C23.1415 19.305 23.4165 19.36 23.719 19.4837C24.0215 19.6075 24.3377 19.7862 24.6815 20.02L29.2327 23.2512C29.5902 23.4987 29.8377 23.7875 29.989 24.1312C30.1265 24.475 30.209 24.8187 30.209 25.2037Z"
        stroke="white"
        strokeWidth="1.97107"
        strokeMiterlimit={10}
      />
    </svg>
  );
};
